server:
  port: 8080

spring:
  application:
    name: lms-service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true

  datasource:
    url: jdbc:mysql://localhost:3306/lms_db
    username: root
    password: Singapore88$
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: lms-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: honyicheng@gmail.com
    password: zkomuaxgadmfqmgs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost       # Redis server host (default: localhost)
      port: 6379            # Redis server port (default: 6379)
      timeout: 6000         # Connection timeout in milliseconds (default: 2000ms)  (6 seconds in this case).
      lettuce: # Lettuce client-specific settings
        pool: # Connection pool configuration
          max-active: 10    # Maximum active connections (default: 8)
          max-idle: 5       # Maximum idle connections (default: 8)
          min-idle: 1       # Minimum idle connections (default: 0)
          max-wait: -1      # Maximum wait time for a connection (-1 = infinite)

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li89LgRHpi0amgLR
            client-secret: d58c27db0e3e53541140f39e396c069900878f7b
            scope: read:user,user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
#            redirect-uri:  http://localhost:5173/oauth2/redirect
            client-name: GitHub
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # 256-bit key
  expiration: 86400000 # 1 day
  refresh-token:
    expiration=604800000 # 7 days

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
  file:
    name: logs/lms.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
app:
  oauth2:
    redirect-uri: http://localhost:5173/oauth2/redirect
